name: LocalStack Benchmark
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "51 04 * * *"

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init localstack

      - uses: docker/setup-buildx-action@v2

      - name: Docker build
        run: |
          cd localstack

          # Ensure exclusive cache access for apt and pip
          sed -i 's/--mount=type=cache/--mount=type=cache,sharing=locked/g' ./Dockerfile

          python3 -m setuptools_scm

          docker buildx build \
            --build-arg LOCALSTACK_PRE_RELEASE=0 \
            --build-arg LOCALSTACK_BUILD_GIT_HASH=$(git rev-parse --short HEAD) \
            --build-arg=LOCALSTACK_BUILD_DATE=$(date -u +"%Y-%m-%d") \
            --build-arg=LOCALSTACK_BUILD_VERSION=$(python3 -m setuptools_scm) \
            --add-host="localhost.localdomain:127.0.0.1" \
            -t localstack/localstack:latest . -f ./Dockerfile

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init localstack

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - name: Docker build
        run: |
          cd localstack

          # Ensure exclusive cache access for apt and pip
          sed -i 's/--mount=type=cache/--mount=type=cache,sharing=locked/g' ./Dockerfile

          python3 -m setuptools_scm

          # Based on `make docker-build` but use default build cache (in remote builder)
          docker buildx build \
            --build-arg LOCALSTACK_PRE_RELEASE=0 \
            --build-arg LOCALSTACK_BUILD_GIT_HASH=$(git rev-parse --short HEAD) \
            --build-arg=LOCALSTACK_BUILD_DATE=$(date -u +"%Y-%m-%d") \
            --build-arg=LOCALSTACK_BUILD_VERSION=$(python3 -m setuptools_scm) \
            --add-host="localhost.localdomain:127.0.0.1" \
            -t localstack/localstack:latest . -f ./Dockerfile

  notify-failures:
    name: Notify on build failures
    needs:
      - docker-build
      - nsc-build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: failure() && needs.docker-build.result == 'success' && needs.nsc-build.result == 'failure'
    steps:
      - uses: ruby/action-slack@v3.2.1
        with:
          payload: |
            {
              "attachments": [{
                "title": "Namespace build failed while Docker build passed! Check now: ${{ job.status }}: ${{ github.workflow }}",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "See the link",
                "fields": [],
                "footer": "",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
